name: Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Push to dockerhub
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: fabiobentoluiz/libfprint_web
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: ./docker/Dockerfile_enroll
